apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-burn
spec:
  template:
    spec:
      containers:
      - name: gpu-burn
        image: ghcr.io/kuoss/gpu-burn:v0.0.0-23.08
        args: ["./gpu_burn", "300"]
        resources:
          limits:
            nvidia.com/gpu: 2
      restartPolicy: Never
