name: ci
on:
  push:
    tags:        
    - 'v*'
jobs:
  push10: # 10.2
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - id: meta
      run: |
        CUDA_VERSION=10.2
        IMAGE_DISTRO=ubi7
        TAG=${GITHUB_REF#refs/tags/}
        IMAGE1=ghcr.io/kuoss/gpu-burn:$TAG-cuda$CUDA_VERSION
        IMAGE2=ghcr.io/kuoss/gpu-burn:cuda$CUDA_VERSION
        echo "CUDA_VERSION=$CUDA_VERSION" >> $GITHUB_OUTPUT
        echo "IMAGE_DISTRO=$IMAGE_DISTRO" >> $GITHUB_OUTPUT
        echo "TAG=$TAG"                   >> $GITHUB_OUTPUT
        echo "IMAGE1=$IMAGE1"             >> $GITHUB_OUTPUT
        echo "IMAGE2=$IMAGE2"             >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
      with:
        repository: wilicc/gpu-burn
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Build image
      run: |
        sed 's|FROM nvidia/cuda|FROM nvcr.io/nvidia/cuda|g' -i Dockerfile
        docker build --build-arg CUDA_VERSION=${{ steps.meta.outputs.CUDA_VERSION }} --build-arg IMAGE_DISTRO=${{ steps.meta.outputs.IMAGE_DISTRO }} . -t ${{ steps.meta.outputs.IMAGE1 }}
    - name: Push image
      run: |
        docker push ${{ steps.meta.outputs.IMAGE1 }}
        docker tag ${{ steps.meta.outputs.IMAGE1 }} ${{ steps.meta.outputs.IMAGE2 }}; docker push ${{ steps.meta.outputs.IMAGE2 }}

  push11: # 11.8.0
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - id: meta
      run: |
        CUDA_VERSION=11.8.0
        IMAGE_DISTRO=ubi8
        TAG=${GITHUB_REF#refs/tags/}
        IMAGE1=ghcr.io/kuoss/gpu-burn:$TAG-cuda$CUDA_VERSION
        IMAGE2=ghcr.io/kuoss/gpu-burn:cuda$CUDA_VERSION
        echo "CUDA_VERSION=$CUDA_VERSION" >> $GITHUB_OUTPUT
        echo "IMAGE_DISTRO=$IMAGE_DISTRO" >> $GITHUB_OUTPUT
        echo "TAG=$TAG"                   >> $GITHUB_OUTPUT
        echo "IMAGE1=$IMAGE1"             >> $GITHUB_OUTPUT
        echo "IMAGE2=$IMAGE2"             >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
      with:
        repository: wilicc/gpu-burn
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Build image
      run: |
        sed 's|FROM nvidia/cuda|FROM nvcr.io/nvidia/cuda|g' -i Dockerfile
        docker build --build-arg CUDA_VERSION=${{ steps.meta.outputs.CUDA_VERSION }} --build-arg IMAGE_DISTRO=${{ steps.meta.outputs.IMAGE_DISTRO }} . -t ${{ steps.meta.outputs.IMAGE1 }}
    - name: Push image
      run: |
        docker push ${{ steps.meta.outputs.IMAGE1 }}
        docker tag ${{ steps.meta.outputs.IMAGE1 }} ${{ steps.meta.outputs.IMAGE2 }}; docker push ${{ steps.meta.outputs.IMAGE2 }}

  push12: # 12.2.0
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - id: meta
      run: |
        CUDA_VERSION=12.2.0
        IMAGE_DISTRO=ubi8
        TAG=${GITHUB_REF#refs/tags/}
        IMAGE1=ghcr.io/kuoss/gpu-burn:$TAG-cuda$CUDA_VERSION
        IMAGE2=ghcr.io/kuoss/gpu-burn:$TAG
        IMAGE3=ghcr.io/kuoss/gpu-burn:cuda$CUDA_VERSION
        IMAGE4=ghcr.io/kuoss/gpu-burn:latest
        echo "CUDA_VERSION=$CUDA_VERSION" >> $GITHUB_OUTPUT
        echo "IMAGE_DISTRO=$IMAGE_DISTRO" >> $GITHUB_OUTPUT
        echo "TAG=$TAG"                   >> $GITHUB_OUTPUT
        echo "IMAGE1=$IMAGE1"             >> $GITHUB_OUTPUT
        echo "IMAGE2=$IMAGE2"             >> $GITHUB_OUTPUT
        echo "IMAGE3=$IMAGE3"             >> $GITHUB_OUTPUT
        echo "IMAGE4=$IMAGE4"             >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
      with:
        repository: wilicc/gpu-burn
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Build image
      run: |
        sed 's|FROM nvidia/cuda|FROM nvcr.io/nvidia/cuda|g' -i Dockerfile
        docker build --build-arg CUDA_VERSION=${{ steps.meta.outputs.CUDA_VERSION }} --build-arg IMAGE_DISTRO=${{ steps.meta.outputs.IMAGE_DISTRO }} . -t ${{ steps.meta.outputs.IMAGE1 }}
    - name: Push image
      run: |
        docker push ${{ steps.meta.outputs.IMAGE1 }}
        docker tag ${{ steps.meta.outputs.IMAGE1 }} ${{ steps.meta.outputs.IMAGE2 }}; docker push ${{ steps.meta.outputs.IMAGE2 }}
        docker tag ${{ steps.meta.outputs.IMAGE1 }} ${{ steps.meta.outputs.IMAGE3 }}; docker push ${{ steps.meta.outputs.IMAGE3 }}
        docker tag ${{ steps.meta.outputs.IMAGE1 }} ${{ steps.meta.outputs.IMAGE4 }}; docker push ${{ steps.meta.outputs.IMAGE4 }}
